# Site settings
title: Software engineering blog
email: oleg.stadnichenko@gmail.com
description: >
  Information about software development, architecture and other technical things.
baseurl: "/site"
url: "http://oleg-sta.github.io" # the base hostname & protocol for your site
github_username:  oleg-sta
facebook_username: oleg.sta
linkedin_username: https://www.linkedin.com/in/oleg-stadnichenko

markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-minimal