# Site settings
title: Software engineering blog
my_name: Oleg Stadnichenko
email: oleg.stadnichenko@gmail.com
description: >
  Information about software development, architecture and other technical things.
baseurl: "/site"
url: "http://oleg-sta.github.io/site"
github_username:  oleg-sta
facebook_username: oleg.sta
linkedin_username: oleg-stadnichenko
medium_username: stoleg
twitter_username: oleg_sta

markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-minimal